from enum import Enum

class TipoNodo(Enum):
    PRINT =  'PRINT'
    VARIABLE =  'VARIABLE'
    INSTRUCCION =  'INSTRUCCION'
    OPERADOR_BINARIO = 'OPERADOR_BINARIO'
    OPERADOR_UNARIO = 'OPERADOR_UNARIO'
    TERMINAL = 'TERMINAL'
